In [54]:
import matplotlib.pyplot as plt
import pandas as pd
import collections
import string
import numpy as np
from numpy import matrix
from numpy import linalg
%matplotlib inline

from cipher import *
from cipherbreak import *

c6a = open('2014/6a.ciphertext').read()
c6b = open('2014/6b.ciphertext').read()

In [3]:
key_a, score = railfence_break(sanitise(c6a))
key_a, score

(3, -2314.997881051078)

In [4]:
' '.join(segment(railfence_decipher(sanitise(c6a), key_a)))

'mark the last message told usa lot the scuttling equipment is designed to pump water in and out of the vessel like a submarine dive control but clearly they werent planning to turn a container ship into a sub this ship is a largescale version of something i have seen in the caribbean drug runners use a similar technique to get below radar coverage for inshore runs sinking the vessel so that the deck remains just below the wave tops the fda pirates seem more interested in staying away from shore but getting close enough to track and record electronic communications without detection i am guessing this scuttling system is what they call nautilus in their log but i am still baffled by the references to seahorse the next page of the log looks harder to crack but the cipher clerk tells me it is a hill cipher and that they must have been in a hurry or have been enciphering by hand since they just used a two by two matrix actually we have been pretty lax with our security and i think the nex

In [7]:
c6bs = sanitise(c6b)
c6bs

'hwssswxfewhhrfewpdrvttdhxbccleayphalnadhiehaoudrotwnrrvysabjlttbaytmelrkaidopthatlelrtwaamaneksvvzrvllatkcrjquicizgtoqcpnrrkttowandqehtqrvtbaydqealannohulanuzlwextlvjrvivhnohdqmgykaclmswrupdetfioftfelhzpxhaswftwprrsweiseohefpdrvttnvagdvswgoerbetnharvaeevtlltbmgaiatgelinmdawevhatterdhrznbnvoutnefoteveaehlaymhacglzeptvvdimworfisgtuzlwibeqohubtghamqornjnnrumqvjtxeltfovgawdaeevllgrtxibgtibevmpsaateoasevaeyqohameonncfuidoefafattemuimnflznbekofobrliaehhauihnnnwzaeevtlltpaalnanvtzlzuucptaelinanpaahewfthaosetaribnbnvhaevdhyytlmuxb'

In [17]:
c6b_nums = [ord(c) - ord('a') for c in c6bs]
c6b_nums

[7,
 22,
 18,
 18,
 18,
 22,
 23,
 5,
 4,
 22,
 7,
 7,
 17,
 5,
 4,
 22,
 15,
 3,
 17,
 21,
 19,
 19,
 3,
 7,
 23,
 1,
 2,
 2,
 11,
 4,
 0,
 24,
 15,
 7,
 0,
 11,
 13,
 0,
 3,
 7,
 8,
 4,
 7,
 0,
 14,
 20,
 3,
 17,
 14,
 19,
 22,
 13,
 17,
 17,
 21,
 24,
 18,
 0,
 1,
 9,
 11,
 19,
 19,
 1,
 0,
 24,
 19,
 12,
 4,
 11,
 17,
 10,
 0,
 8,
 3,
 14,
 15,
 19,
 7,
 0,
 19,
 11,
 4,
 11,
 17,
 19,
 22,
 0,
 0,
 12,
 0,
 13,
 4,
 10,
 18,
 21,
 21,
 25,
 17,
 21,
 11,
 11,
 0,
 19,
 10,
 2,
 17,
 9,
 16,
 20,
 8,
 2,
 8,
 25,
 6,
 19,
 14,
 16,
 2,
 15,
 13,
 17,
 17,
 10,
 19,
 19,
 14,
 22,
 0,
 13,
 3,
 16,
 4,
 7,
 19,
 16,
 17,
 21,
 19,
 1,
 0,
 24,
 3,
 16,
 4,
 0,
 11,
 0,
 13,
 13,
 14,
 7,
 20,
 11,
 0,
 13,
 20,
 25,
 11,
 22,
 4,
 23,
 19,
 11,
 21,
 9,
 17,
 21,
 8,
 21,
 7,
 13,
 14,
 7,
 3,
 16,
 12,
 6,
 24,
 10,
 0,
 2,
 11,
 12,
 18,
 22,
 17,
 20,
 15,
 3,
 4,
 19,
 5,
 8,
 14,
 5,
 19,
 5,
 4,
 11,
 7,
 25,
 15,
 23,
 7,
 0,
 18,
 22,
 5,
 19,
 22,
 15,
 17,
 17,
 18,
 22,
 

In [106]:
m = np.matrix([[7,8], [11,11]])
m

matrix([[ 7,  8],
        [11, 11]])

In [107]:
np.linalg.det(m)

-11.000000000000002

In [108]:
m.I

matrix([[-1.        ,  0.72727273],
        [ 1.        , -0.63636364]])

In [37]:
v = np.matrix([[7], [22]])
v

matrix([[ 7],
        [22]])

In [46]:
c = (m*v) % 26
c

matrix([[9],
        [5]])

In [48]:
np.linalg.solve(m, c) % 26

matrix([[  7.],
        [ 22.]])

In [40]:
m*v

matrix([[ 87],
        [109]])

In [41]:
(m*v)%26

matrix([[9],
        [5]])

In [42]:
np.linalg.solve(m, (m*v)%26)%26

matrix([[  7.],
        [ 22.]])

In [51]:
len(m)

2

In [181]:
def hill_encipher(matrix, message_letters, fillvalue='a'):
    n = len(matrix)
    sanitised_message = sanitise(message_letters)
    if len(sanitised_message) % n != 0:
        padding = fillvalue[0] * (n - len(sanitised_message) % n)
    else:
        padding = ''
    message = [ord(c) - ord('a') for c in sanitised_message + padding]
    message_chunks = [message[i:i+n] for i in range(0, len(message), n)]
    # message_chunks = chunks(message, len(matrix), fillvalue=None)
    enciphered_chunks = [((matrix * np.matrix(c).T).T).tolist()[0] for c in message_chunks]
    return ''.join([chr(int(round(l)) % 26 + ord('a')) for l in sum(enciphered_chunks, [])])

In [156]:
hill_encipher(m, 'hellothere')

'drjiqzdrvx'

In [68]:
msg = [ord(c) - ord('a') for c in 'hellothere']
msg

[7, 4, 11, 11, 14, 19, 7, 4, 17, 4]

In [112]:
msgc = [msg[i:i+len(m)] for i in range(0, len(msg), len(m))]
msgc

[[7, 11], [14, 25], [21, 14], [7, 11], [11, 15], [0, 0]]

In [87]:
((m*np.matrix(msgc[0]).T).T % 26).tolist()[0]

[7, 11]

In [195]:
def hill_decipher(matrix, message, fillvalue='a'):
    adjugate = linalg.det(matrix)*linalg.inv(matrix)
    inverse_determinant = modular_division_table[int(round(linalg.det(matrix))) % 26][1]
    inverse_matrix = (inverse_determinant * adjugate) % 26
    return hill_encipher(inverse_matrix, message, fillvalue)                                                 

In [161]:
hill_decipher(m, 'drjiqzdrvx')

'hellothere'

In [114]:
msg = [ord(c) - ord('a') for c in 'drjiqzdrvxaa']
msg

[3, 17, 9, 8, 16, 25, 3, 17, 21, 23, 0, 0]

In [115]:
msgc = [msg[i:i+len(m)] for i in range(0, len(msg), len(m))]
msgc

[[3, 17], [9, 8], [16, 25], [3, 17], [21, 23], [0, 0]]

In [116]:
(np.linalg.solve(m, np.matrix(msgc[0]).T).T % 26)

matrix([[  9.36363636,  18.18181818]])

In [142]:
m_adj = linalg.det(m)*linalg.inv(m)
m_adj

matrix([[ 11.,  -8.],
        [-11.,   7.]])

In [148]:
modular_division_table[int(round(linalg.det(m))) % 26][1]

7

In [150]:
m_inv = (modular_division_table[int(round(linalg.det(m))) % 26][1] * m_adj) % 26
m_inv

matrix([[ 25.,  22.],
        [  1.,  23.]])

In [157]:
hill_encipher(m_inv, 'drjiqzdrvx')

'hellothere'

In [120]:
np.dot(m , 1/linalg.det(m) * mc)

matrix([[ 1.,  0.],
        [ 0.,  1.]])

In [122]:
ml = np.matrix([[6, 24, 1], [13, 16, 10], [20, 17, 15]])
ml

matrix([[ 6, 24,  1],
        [13, 16, 10],
        [20, 17, 15]])

In [137]:
ml_adj = linalg.det(ml)*linalg.inv(ml) % 26
ml_adj

matrix([[ 18.,  21.,  16.],
        [  5.,  18.,   5.],
        [  5.,  14.,  18.]])

In [138]:
modular_division_table[int(linalg.det(ml) % 26)][1]

25

In [139]:
ml_inv = (modular_division_table[int(linalg.det(ml) % 26)][1] * ml_adj) % 26
ml_inv

matrix([[  8.,   5.,  10.],
        [ 21.,   8.,  21.],
        [ 21.,  12.,   8.]])

In [193]:
hill_encipher(ml, 'hello there')

'tfjflpznvyac'

In [196]:
hill_decipher(ml, 'tfjflpznvyac')

'hellothereaa'

In [182]:
hill_encipher(ml, 'act')

'poh'

In [192]:
hill_decipher(ml, 'poh')

[[  8.   5.  10.]
 [ 21.   8.  21.]
 [ 21.  12.   8.]]


'act'

In [180]:
[chr(int(round(i)) % 26 + ord('a')) for i in (ml_inv * np.matrix([ord(c) - ord('a') for c in 'poh']).T).T.tolist()[0]]

['a', 'c', 't']

In [184]:
hill_encipher(ml_inv, 'poh')

'act'

In [203]:
len([list(m) for m in itertools.product([list(r) for r in itertools.product(range(26), repeat=3)], repeat=3)])

KeyboardInterrupt: 

In [202]:
(3**3)**3

19683

In [206]:
[np.matrix(list(m)) for m in itertools.product([list(r) for r in itertools.product(range(3), repeat=2)], repeat=2)]

[matrix([[0, 0],
         [0, 0]]), matrix([[0, 0],
         [0, 1]]), matrix([[0, 0],
         [0, 2]]), matrix([[0, 0],
         [1, 0]]), matrix([[0, 0],
         [1, 1]]), matrix([[0, 0],
         [1, 2]]), matrix([[0, 0],
         [2, 0]]), matrix([[0, 0],
         [2, 1]]), matrix([[0, 0],
         [2, 2]]), matrix([[0, 1],
         [0, 0]]), matrix([[0, 1],
         [0, 1]]), matrix([[0, 1],
         [0, 2]]), matrix([[0, 1],
         [1, 0]]), matrix([[0, 1],
         [1, 1]]), matrix([[0, 1],
         [1, 2]]), matrix([[0, 1],
         [2, 0]]), matrix([[0, 1],
         [2, 1]]), matrix([[0, 1],
         [2, 2]]), matrix([[0, 2],
         [0, 0]]), matrix([[0, 2],
         [0, 1]]), matrix([[0, 2],
         [0, 2]]), matrix([[0, 2],
         [1, 0]]), matrix([[0, 2],
         [1, 1]]), matrix([[0, 2],
         [1, 2]]), matrix([[0, 2],
         [2, 0]]), matrix([[0, 2],
         [2, 1]]), matrix([[0, 2],
         [2, 2]]), matrix([[1, 0],
         [0, 0]]), matrix([[1, 0],
   

In [215]:
all_matrices = [np.matrix(list(m)) for m in itertools.product([list(r) for r in itertools.product(range(26), repeat=2)], repeat=2)]
valid_matrices = [m for m, d in zip(all_matrices, (int(round(linalg.det(m))) for m in all_matrices))
                  if d != 0
                  if d % 2 != 0
                  if d % 13 != 0 ]
len(valid_matrices)

157248

In [216]:
%%timeit
[m for m, d in zip(all_matrices, (int(round(linalg.det(m))) for m in all_matrices))
                  if d != 0
                  if d % 2 != 0
                  if d % 13 != 0 ]
print('done')

done
done
done
done
1 loops, best of 3: 10 s per loop


In [217]:
%%timeit
[m for m in all_matrices
                  if int(round(linalg.det(m))) != 0
                  if int(round(linalg.det(m))) % 2 != 0
                  if int(round(linalg.det(m))) % 13 != 0 ]
print('done')

done
done
done
done
1 loops, best of 3: 20.4 s per loop
